### ISSUE TITLE
help i beg

### ISSUE THREAD

**Issue by asuerx** [monkeyskid/Tiktok-shares-bot#3]
![image](https://user-images.githubusercontent.com/103267521/164914847-aba961fc-a61d-443a-bb6c-7e726918f0be.png)
Im stuck on this part

**Comment by monkeyskid** [comment]
you're supposed to use it like this:
run `go run .`
then enter the video id and threads

**Comment by asuerx** [comment]
it still doesn't work can u send a screenshot of u doing it

**Comment by monkeyskid** [comment]
here
![](https://cdn.has-cool.pics/QRyo0V3ZAGu62nlRalQtdGAv1.png?k=57ih9vyPptkfFfiG)
